### ISSUE TITLE
Warning: buffer *goals* not killed; still associated with prover process

### ISSUE THREAD

**Issue by maximedenes** [psteckler/ProofGeneral#1]
Steps to reproduce: load a .v file, play one step (ctrl+c ctrl+n), then try to restart the coq process (ctrl+c ctrl+x).

**Comment by psteckler** [comment]
I removed the kill-buffer-hook for the goals buffer, which allows the kill call to succeed.

Also, the *coq-log* buffer was not in the list of buffers to kill on shutdown. I added that.

If you can verify the fix, I'll close the issue.

**Comment by maximedenes** [comment]
This problem is fixed, but did you try to restart Coq after killing it? On my machine it doesn't work, but it may be related to the other problems I have, so I'll report them first.

**Comment by psteckler** [comment]
After killing Coq, I was able to single-step through file, and after killing it again, I was able to process the whole file. I used the file ProofGeneral/github-issues/1.v.

**Comment by maximedenes** [comment]
ok, this seems fixed.
