### ISSUE TITLE
Wrong backtrack when editing

### ISSUE THREAD

**Issue by jhjourdan** [psteckler/ProofGeneral#102]
Consider the following Coq script:
```
Lemma L : False. Proof. exact I.  Qed.
Lemma L2 : True. Proof. exact I.  Qed.
```

Then C-c C-b. Then add a letter immediately before the `I` of the first line.

It appears that `exact` stays in blue even though the tactic has been edited.

**Comment by jhjourdan** [comment]
Moreover, editing `exact` after that shows strange error messages in the mini buffer:

```
  backtrace()
  proof-script-after-change-function(31 32 0)
  self-insert-command(1)
  funcall-interactively(self-insert-command 1)
  call-interactively(self-insert-command nil nil)
  command-execute(self-insert-command)

  backtrace()
  proof-script-after-change-function(28 29 0)
  self-insert-command(1)
  funcall-interactively(self-insert-command 1)
  call-interactively(self-insert-command nil nil)
  command-execute(self-insert-command)
```

**Comment by psteckler** [comment]
Yep, I left debugging code in my commit, my mistake. It's removed now.

I'll investigate the actual error.

**Comment by psteckler** [comment]
Try editing anywhere in the first `exact I`, it should all become white now.

The algorithm to find the preceding statement was looking for whitespace, it should have been looking for a period/full-stop.

**Comment by jhjourdan** [comment]
Thanks, this is fixed now.
