### ISSUE TITLE
Retraction when Coq looping, can't process script

### ISSUE THREAD

**Issue by psteckler** [psteckler/ProofGeneral#12]
With a looping script, like this one:

Goal nat.
repeat (generalize 0).

after retracting the buffer, can't step through the script again.

**Comment by psteckler** [comment]
I came up with a solution here, using the complete-responses mechanism I installed.

If the response is complete, a retraction works as before (basically, doing a Goto to the start of the file).
Otherwise, restart Coq. The other choice might have been to do an interrupt, but that leads to a fail value, which doesn't seem like a good idea.

I lowered the timeout for a restart from 5 seconds to 1, which seems OK, and is less annoying.

**Comment by gares** [comment]
I'm not sure I'm following here.  Why do you need to restart Coq?  I guess PG users are used to hit ^C whenever Coq is not responding.  Note that in a large script hitting ^C may leave Coq in a state that a fresh instance of Coq can only reach after minutes (i.e. you are in the middle of a large file).

**Comment by psteckler** [comment]
If Coq is looping, and PG tries to send an Edit_at 1, the call will remain
in the queue, because the transaction code will not send anything until the
last  value has been received.

In the worst case (meaning when Coq is looping), the restart of Coq will
take just over 1 second, because it uses more drastic means if sending a
Quit doesn't work after 1 second.

This issue is only about retraction, though, and the restart happens only
when a transaction is incomplete. That could happen while a user is
processing a large file, of course, though I think it's more likely the
user will hit C-c C-c to do an interrupt rather than try to retract the
file.

**Comment by psteckler** [comment]
I can probably make it so that the restart-on-retraction doesn't even try the Quit, and just uses the drastic means, so there will be no delay.

**Comment by psteckler** [comment]
I've made that change.
