### ISSUE TITLE
Non delegated proofs

### ISSUE THREAD

**Issue by gares** [psteckler/ProofGeneral#13]
I don't have the exact file (it was on a colleague's machine) but something like that misbihaves
```
Section foo.
Variable x: nat.

Lemma test : 3 = 3.
Proof.
exact I.
Qed.

End foo.

Lemma jump_here : True.
```
PG jumps back to the broken exact I.
If you annotate the Proof line of test with "Proof using x" then it works.

From the UI perspective, both scripts are identical, but one is slower, since Coq evaluates the proof synchronously.  For some reasons PG cannot step over the error in such case.

**Comment by gares** [comment]
Just to be clear, this script works
```
Section foo.
Variable x: nat.

Lemma test : 3 = 3.
Proof using x.
exact I.
Qed.

End foo.

Lemma jump_here : True.
```

Just jump at the end.

I've no idea what goes wrong, since the two executions should only differ in the sequence of the messages.

**Comment by gares** [comment]
The bug concerns @barbichu that kindly tested the new async stuff

**Comment by psteckler** [comment]
In 8.6, CoqIDE gives the same behavior on this file. And with the "using x", processing goes to the end of the script.

Without the "using x", the "End foo." triggers a fail-value, which causes PG to send an Edit_at. It looks like CoqIDE does the same.

With the "using x", there's no fail-value, just a feedback with an "error" message.

**Comment by gares** [comment]
Oh, you are right.  For the section to End, you need either to have the "using ..." annotation or the proof term.

So no bug, just a nasty behavior.

@barbichu, I think you want to give a look at the "using. .." syntax in Coq's manual (it is not trivial).
