### ISSUE TITLE
Very slow compared to normal PG (maybe bc. of debug output?)

### ISSUE THREAD

**Issue by Janno** [psteckler/ProofGeneral#17]
First of all, thank you so much for starting this fork. It's like an alpha version of Christmas! :)

Now, my main problem with this version of PG is that it is extremely slow. I think the reason might be the amount of debug output. Is there a way to disable it?

Thanks,
Jan-Oliver

**Comment by psteckler** [comment]
Hi Jan-Oliver -- You can disable the debug messages by shadowing the `message' Elisp function. In the file HOWTO-USE, look at the .emacs entry, and unquote the defun for `message'.

See if that speeds up things.

I plan to make it easier to remove the debug messages soon, by the way.

**Comment by psteckler** [comment]
I've just pushed code that disables the debugging output by default.

Also, you can disable the traffic logging, if things are still too slow. How to do that is now described in the HOWTO-USE file.

**Comment by psteckler** [comment]
I'm going to close this issue, since I assume the debugging output was responsible for the slowdown.
