### ISSUE TITLE
cursor trails current line by 1 when single stepping

### ISSUE THREAD

**Issue by jonleivent** [psteckler/ProofGeneral#18]
PG version dd04741

When single stepping through a script, the cursor is placed at the end of the previous line.  Moving it by hand to the end of the most recently processed line doesn't correct, as the next single step puts it again at the end of the previous line.

I'm using Emacs 24.4.1, Coq 8.6 (3e794be).

**Comment by psteckler** [comment]
When I run it, the cursor is placed at the beginning of the previous line. In the main PG repo, it's placed at the end of the previous line. Is that the desired behavior?

**Comment by psteckler** [comment]
Actually, I think my main repo was not clean. I cleaned up the repo, and now I see the cursor at the beginning of the line just past the processed region.

**Comment by psteckler** [comment]
Tracked this down, the "queue span" is not being set properly. Looking into why.

**Comment by psteckler** [comment]
I'd commented out some code that set the queue span endpoints. Removing the comment appears to fix the issue.
