### ISSUE TITLE
PG incompatible with -debug flag

### ISSUE THREAD

**Issue by maximedenes** [psteckler/ProofGeneral#2]
Steps to reproduce : open a file containing

Goal True.
Proof.
exact I.
Qed.

Definition bar := false.

Put the cursor at the end of the file, then ctrl+c ctrl+enter. The processed region stops at  Qed.

Going step by step from the beginning of the file is even worse, we get stuck on "Proof".

**Comment by psteckler** [comment]
Naturally, I don't see any failure here. I've tried (a slightly modified) v8.6 and v8.5pl2, and I'm able to single-step and process the whole file successfully for both versions of coqtop.

To check I'm running the current code, I did:

  git diff 
  [no difference shown]

and

  make clean && make

I'm guessing that coqtop is not starting properly. Can you verify that it's running using "ps aux | grep coqtop"? Also, what do you see in the *coq-log* buffer?

**Comment by maximedenes** [comment]
Ok, I found where the problem comes from: I use coqtop with the -debug flag, to track down some Coq bugs. It seems that -debug confuses the XML proof general. Probably still qualifies as a bug.

**Comment by psteckler** [comment]
Aha, I'll see what happens when I add that flag.

**Comment by psteckler** [comment]
The -debug flag prints output to stderr, which is sent to the process filter in PG.

So this is the same problem as in issue #3!

Apparently, there's no way to have the process filter not receive stderr, so either we need to prevent the stderr output, or redirect before it reaches Emacs.

**Comment by psteckler** [comment]
I've committed a fix for this. The code now redirects stderr to /dev/null.
