### ISSUE TITLE
when single stepping a proof, update goal before unhighlighting current step

### ISSUE THREAD

**Issue by jonleivent** [psteckler/ProofGeneral#21]
In 284b242, when single stepping through a proof, the current tactic step is highlighted bright blue, executed, then unhighlighted to pale blue (locked), then lastly the goal window is updated.  This is rather jarring, as there is sometimes enough of a delay between the final unhighlighting of the tactic and the updating of the goal window that one wonders if the tactic worked properly or not.   Maybe it just takes some getting used to, but I think it would be more intuitive if the order of the last two steps were reversed - update the goal before unhighlighting the tactic step.

**Comment by psteckler** [comment]
In the XML protocol, a statement is submitted using the Add call. Then you get messages indicating that the statement is in-process (PG colors it dark blue), another saying it's been processed (the dark blue is removed), then a message saying that the submission is successful. When PG receives that last one, it requests the goals. 

We could delay removing the dark blue until after goal request has been sent and the response received, but that adds complexity. Also it would mean treating the single-step case differently than the multiple-step case, where the dark blue is removed upon receipt of the processed message for each statement.

**Comment by jonleivent** [comment]
Is the delay between the last highlight update and the goal window update always reliably short?  If it is, then this might just be the cost of doing business with the new interface.  If it is not reliably short, then maybe the added complexity is worth it - but you'll need many more opinions than mine to decide.

Another way you could do this is to somehow highlight the goal window immediately when a step is issued, then unhighlight it when the goal window has finished changing due to that step.  Might that require less complexity?  For instance, slightly gray out the goal window, or pink it or some other color that indicates "not ready yet" but doesn't grossly impede readability.

**Comment by psteckler** [comment]
The delay after receive the last "processed" feedback and getting the goal should be short, but of course, the time from submitting the statement to getting that feedback can be arbitrarily long.

We could dim the *goals* buffer when submitting a statement, then un-dim it when printing the goal. 

We should discuss again later; there are still some serious bugs to work on.
Let's discuss again when

**Comment by jonleivent** [comment]
I've been examining this again (using wavl-noauto.v, which has many small tactic steps).  I'm not sure large changes to the display are called for - they might be too jarring.

I think that whatever highlighting is done to indicate that the goals window is not yet updated probably should stick to being on the tactic.  If you can't delay the removal of the dark blue highlight, maybe you can instead have it go from dark blue to something intermediate to light blue?

**Comment by psteckler** [comment]
With the current coloring regime, is this still an issue?

I note that the goal printing and the dark-blue-to-pale-blue transition are more-or-less simultaneous when single-stepping.

**Comment by jonleivent** [comment]
Yes - it seems a lot better now.  Not quite simultaneous, but it is fast enough so that one doesn't get confused.

**Comment by psteckler** [comment]
Is it OK to close this as an issue, then? Or do you think there's still some change needed?

**Comment by jonleivent** [comment]
Close it.
