### ISSUE TITLE
Incorrect interaction with proof-prog-name-ask 't

### ISSUE THREAD

**Issue by JasonGross** [psteckler/ProofGeneral#23]
If I set `proof-prog-name-ask` to `'t`, then evaluation begins before I respond to the prompt about program name, and when I select a Coq program, I get the error message `Symbol's value as variable is void: proof-shell-unicode`

Moreover, I get queried about the Coq binary every time I single step forward, which is wrong.  This makes this version of PG completely unusable if I want to use multiple versions of Coq in the same emacs.

**Comment by JasonGross** [comment]
Actually, most of that seems to be a result of #24; the behavior without company-coq seems to be that PG ignores `proof-prog-name-ask`.

**Comment by cpitclaudel** [comment]
Unrelated, but: `t` doesn't need quoting. That is, you can write `t` instead of `'t` :)

**Comment by psteckler** [comment]
Right, the code that looks at that option was in proof-shell.el, which interacts with the coqtop REPL. I'll have to add something similar for the current setup.

Elisp trivia: (eq t 't) => t :-)

**Comment by psteckler** [comment]
Fix committed, please try it.

**Comment by JasonGross** [comment]
Thanks!  Seems fixed.

**Comment by JasonGross** [comment]
This issue seems to have come back (tested with bd288c967800b697f6f06a30538f5bfd26e77bcb); I'm getting queried about the binary on every step forward, and get `Symbol's value as variable is void: proof-shell-unicode` again.

**Comment by JasonGross** [comment]
Ooops, seems to only show up with company-coq.
