### ISSUE TITLE
Failure to jump to the character location on error

### ISSUE THREAD

**Issue by JasonGross** [psteckler/ProofGeneral#25]
In vanilla PG, if I try to evaluate
```coq
Goal True = @eq.
```
it fails, and the cursor is placed immediately before `@eq`.  In this branch, it is placed at the beginning of the line.  In this case, it's not bad, but if my definition is a few dozen (or a few hundred) lines of code, this regression is enough to make me not willing to work in this branch.  Let me know when this is fixed, and I'll try it out again.

**Comment by psteckler** [comment]
I've committed a fix. It's a bit tricky, because things happen after the error is highlighted that affect the cursor position. There may be remaining bugs around this issue.

**Comment by JasonGross** [comment]
Here's another bug.  In
```coq
Definition x := 1.
Section foo.
  Inductive x := a.
End foo.
Section bar.
  Context (y : nat).
  Goal True.
    constructor.
  Qed.
End bar.
```
If I go to the end and do `proof-goto-point`, then the cursor stays at the end, and I get no indication that there's an error.  (The line gets bolded; it should get colored red, and the cursor should jump to that point.  Or, at least, there should be a setting that makes the cursor jump to that point.  Async is useful for proofs, but is counter-productive for definitions if it hides the fact that I'm editing.)

Another issue: if I then place the cursor before `End foo.` and do `proof-goto-point`, then it moves the cursor to right after `Section foo.`.  This is incorrect; if I start typing `XYZ` before `End`, I should not get `Section foo.YZ ... XEnd foo.`.  It should all go immediately before `End`.

**Comment by psteckler** [comment]
OK, I'll look at these. 

It would be better to file these as separate bugs, rather than append them to an existing issue. That makes it easier to track things.

**Comment by JasonGross** [comment]
#26 and #27

Thanks for being responsive!
