### ISSUE TITLE
Incorrect movement of cursor when editing a locked region with an error in it

### ISSUE THREAD

**Issue by JasonGross** [psteckler/ProofGeneral#27]
In
```coq
Definition x := 1.
Section foo.
  Inductive x := a.
End foo.
Section bar.
  Context (y : nat).
  Goal True.
    constructor.
  Qed.
End bar.
```
If I go to the end and do `proof-goto-point`, and then I then place the cursor before `End foo.` and do `proof-goto-point`, then it moves the cursor to right after `Section foo.`.  This is incorrect; if I start typing `XYZ` before `End`, I should not get `Section foo.YZ ... XEnd foo.`.  It should all go immediately before `End`.

**Comment by psteckler** [comment]
I see what's happening. If you type after the highlighted error, there's a retraction to the state corresponding to the error. But Coq knows this is a bad state, so there's a failure message sent which means, that's not a good state, you meant to go to this other state, the one just before the error, and PG obliges.

I'll have to work out how to avoid this kind of problem.

**Comment by psteckler** [comment]
I've committed a fix, a bit hackish, which may have unintended consequences.

**Comment by psteckler** [comment]
Has this been fixed? Can I close the issue?
