### ISSUE TITLE
Inconsistent behavior around "Inconsistent Assumptions" and other errors of "Require" (8.6)

### ISSUE THREAD

**Issue by JasonGross** [psteckler/ProofGeneral#28]
Consider this script:
```bash
#!/bin/bash
mkdir -p tmp
cd tmp
cat > A.v <<EOF
Definition x := true.
EOF
cat > B.v <<EOF
Require Import Top.A.
Definition y := x.
EOF
cat > C.v <<EOF
Require Import Top.B.
Require Import Coq.Init.Datatypes.
Definition z := 1.
Section foo.
End foo.
EOF
${COQBIN}coqc -q -Q . "Top" A.v || exit 1
${COQBIN}coqc -q -Q . "Top" B.v || exit 1
cat > A.v <<EOF
Definition x := false.
EOF
${COQBIN}coqc -q -Q . "Top" A.v || exit 1
```

If you open `C.v` in emacs and evaluate to the end, it appears as if the `Section` failed:
![image](https://cloud.githubusercontent.com/assets/396076/18687142/a4bd0242-7f33-11e6-936e-bd5e60387a85.png)
If you then evaluate to the end again, it succeeds:
![image](https://cloud.githubusercontent.com/assets/396076/18687151/aefe990a-7f33-11e6-9d34-788cea0dbcd0.png)
If you go to the beginning and do `proof-goto-point`, only the `End` is undone:
![image](https://cloud.githubusercontent.com/assets/396076/18687187/c5866234-7f33-11e6-8896-b3db1df4063e.png)
If you do `proof-goto-point` again from the beginning, only the final line is undone again:
![image](https://cloud.githubusercontent.com/assets/396076/18687202/d488c6c8-7f33-11e6-9966-280506ba477c.png)
If you evaluate to the end and hit `RET` from the beginning of the file, you get this strange lack-of-retraction:
![image](https://cloud.githubusercontent.com/assets/396076/18687243/030685a8-7f34-11e6-90cf-913ba453c0d6.png)
If you start typing in the "locked" region, PG seems to move the cursor around and try to re-evaluate statements of its own choosing
![image](https://cloud.githubusercontent.com/assets/396076/18687282/2ed24bfe-7f34-11e6-9023-5f0c8bbd592e.png)

At no point do you get any feedback that the first `Require Import` failed.

**Comment by psteckler** [comment]
Maxime has reported a perhaps-similar bug with a Require with the CompCert code. Looking into it ...

**Comment by psteckler** [comment]
There's a fail-value returned by coqtop as a result of the first Require, and PG issues an Edit_at to jump back to the top of the script. I suspect it's a corner case issue, where the error is on the first line.

**Comment by psteckler** [comment]
The problem seems to be that the communication with coqtop is not properly interleaving calls and responses, though there's a mechanism meant to insure that. Sigh.

**Comment by psteckler** [comment]
I've worked out the sequence of actions that causes the interleaving to fail. Not yet sure what the fix is.

**Comment by psteckler** [comment]
I've fixed the interleaving issue, but there's still something funny going on.

**Comment by psteckler** [comment]
The remaining problem is due to the fact that the error is at the start of the script. Because there's been no sentence processed, there's no span at the point of the error. The PG fallback behavior in that case is just to undo the last line processed (not sure why that's a good idea).

**Comment by psteckler** [comment]
There were other issues. The main one was that items remained in the local queue after failure, so that they eventually got sent to Coq.

I've committed a fix. The error gets marked differently the first time from subsequent attempts. That has to do with the way the internal queue of script items is processed, and how it sets the end of the locked region.

**Comment by psteckler** [comment]
OK to close?
