### ISSUE TITLE
*response* buffer wraps lines needlessly, and should scroll to the top, not bottom

### ISSUE THREAD

**Issue by JasonGross** [psteckler/ProofGeneral#31]
In vanilla PG:
![image](https://cloud.githubusercontent.com/assets/396076/18687788/87496efa-7f36-11e6-8c2d-b42048d31d94.png)
![image](https://cloud.githubusercontent.com/assets/396076/18687792/8b1b85b8-7f36-11e6-86bb-d397c7082c88.png)

In PG-xml:
![image](https://cloud.githubusercontent.com/assets/396076/18687813/99a4ddaa-7f36-11e6-85ea-5296a2e010c9.png)
![image](https://cloud.githubusercontent.com/assets/396076/18687823/a30e572c-7f36-11e6-9868-c162a1bf0de9.png)

**Comment by psteckler** [comment]
It looks like the fix for #29 leaves the first line at top.

PG is not inserting any newlines into the response. It could be that in the XML protocol with 8.6, there are newlines inserted as part of the richpp mechanism.

See if the problem persists.

**Comment by psteckler** [comment]
Can I close this issue?

**Comment by psteckler** [comment]
Closing ... I just tried a Print command, which left the response buffer scrolled to the top.
