### ISSUE TITLE
PG-xml centers the goal rather than left-aligning it

### ISSUE THREAD

**Issue by JasonGross** [psteckler/ProofGeneral#32]
What's the reason for this?  Is the change intentional?  Also, the indentation on subsequent lines seems wonky, e.g., with
```coq
Goal False.
  do 20 generalize 1.
```

**Comment by psteckler** [comment]
You mean goals specified in script, and not the goal display in the *goals* buffer?

I haven't intentionally made any change in the indentation code, but it's possible I did.

**Comment by psteckler** [comment]
For me, the script snippet above indents the same in vanilla PG and PG-XML.

If you meant the formatting of goals in the \*goals\* buffer, PG receives unformatted goals in an XML structure, rather than pre-formatted from the REPL. So I had to write a formatter for goals. I center the goal within the hyps/goal separator line, 'cuz that's how I would do it in a paper. :-)

**Comment by JasonGross** [comment]
I mean the *goals* buffer:
PG-xml:
![image](https://cloud.githubusercontent.com/assets/396076/18693445/8bae1a16-7f56-11e6-9904-a938a97d8e1c.png)
![image](https://cloud.githubusercontent.com/assets/396076/18693447/8f3fd0f2-7f56-11e6-81d4-ddf8dced2520.png)

Vanilla PG:
![image](https://cloud.githubusercontent.com/assets/396076/18693454/a568c96a-7f56-11e6-8e2d-209f4e2ed21a.png)
![image](https://cloud.githubusercontent.com/assets/396076/18693461/a9961092-7f56-11e6-97b8-5611f55f336c.png)

It surprised me, but I'm sure I'll get used to it if it's here to stay; I have no strong opinions, though I'm curious if @ejgallego or @cpitclaudel have thoughts on the design choice.

**Comment by JasonGross** [comment]
However, the issue with indentation is definitely a bug:
PG-xml:
![image](https://cloud.githubusercontent.com/assets/396076/18693523/1f4acd64-7f57-11e6-81c1-39f64ba1909d.png)

vanilla PG:
![image](https://cloud.githubusercontent.com/assets/396076/18693508/0213d7e0-7f57-11e6-8b28-1be8684ccf88.png)

Note that PG-xml wraps the separator line because it's too long (it should never become that long), and that `nat` is flush left on all but the first line, where it should be aligned with the left of the separator, as in vanilla PG.

**Comment by ejgallego** [comment]
May it be the `richpp` processsing?

**Comment by psteckler** [comment]
I hope that you like the new Unicode separator line in place of the ASCII-equals, at least.

I should be able to fix the indentation bug with multi-line goals, which I don't think is richpp-related.

**Comment by cpitclaudel** [comment]
> I hope that you like the new Unicode separator line in place of the ASCII-equals, at least.

Is it a separate implementation from the one in company-coq?

**Comment by JasonGross** [comment]
> the new Unicode separator line

Indeed, I do :)

**Comment by psteckler** [comment]
Yes, there's a defvar that in coq/coq-server.el that gives the separator char. 

If people use PG without company-coq, such a definition is needed, I think.

**Comment by psteckler** [comment]
I've committed a fix that should handle multi-line goals similarly to vanilla PG.

**Comment by psteckler** [comment]
I've noticed that in company-coq, there are at least a couple of places where the code is looking for a sequence of ASCII-equals.

**Comment by psteckler** [comment]
Can I close this issue? In the company-coq code, it can setq the separator char to an equals sign, which should allow it to work as before.
