### ISSUE TITLE
"Wrong type argument: consp, nil" if you cancel the prompt from proof-prog-name-ask

### ISSUE THREAD

**Issue by JasonGross** [psteckler/ProofGeneral#33]
If I open a file, `C-c C-RET` at the bottom with `proof-prog-name-ask` to `t`, and then, rather than hitting `RET`, hit `C-g`, I get "Wrong type argument: consp, nil" if I try to evaluate to the bottom again.

**Comment by psteckler** [comment]
I've committed a fix to try.

**Comment by psteckler** [comment]
Can I close this issue? I believe it's fixed.
