### ISSUE TITLE
PG-xml says no more goals when there are more subgoals (with bullets)

### ISSUE THREAD

**Issue by jonleivent** [psteckler/ProofGeneral#35]
This is PGxml version 40e991b (Emacs 24.4.1, Coq 8.6 version d907342):

![screenshot-emacs jess home](https://cloud.githubusercontent.com/assets/7363878/18923863/f29bf452-857b-11e6-92a5-9f25f64b2176.png)

Compare to normal PG (version 71be0c6):

![screenshot-emacs jess home-1](https://cloud.githubusercontent.com/assets/7363878/18923934/3bb32bb0-857c-11e6-853b-818743267763.png)

Also note the blank goals window and missing response window info about bullets.

**Comment by psteckler** [comment]
There are a couple of things going on there. After the "exact I" is processed, the goal shows up as a "background goal" in the XML response. These have a different structure in the XML than a foreground goal, which the code wasn't handling. I'm on it ...

The message you see in the \*response\* buffer comes from the coqtop REPL in <infomsg> tags, when the -emacs flag is given to coqtop. The XML doesn't seem to contain this message anywhere; probably it should. I'll file a bug report for Coq.

**Comment by psteckler** [comment]
I tried CoqIDE on this same example, and it shows the same text as in the <infomsg> tags. There's some magic I need so that it shows up in the XML response; investigating.

**Comment by psteckler** [comment]
The background goals should show up now, and they are marked as such. Ditto for shelved, abandoned goals. If there are multiple classes of goals, they should all show up.

Still investigating the <infomsg> information.

**Comment by gares** [comment]
In -emacs, it is the function printing the goals that adds such text

In -ideslave it is *CoqIDE* that adds such sentence based on the structure of the goals (it gets a list of given up, unfocused ...).

Try `git grep 'This subproof'` yourself and scream!

Is that horrible? *YES*. I'd happily merge code in Coq (i.e. shared among all UI) that Feedbacks such piece of info...

**Comment by gares** [comment]
Actually the commit that adds the sentence in CoqIDE admits that it was a quick and dirty hack, so if you have time to properly feedback that info it would be nice.

**Comment by ejgallego** [comment]
Sorry @gares, can you point out to the exact commit you mean?

**Comment by gares** [comment]
1e9ef2c64dcfa916ba3643b219040cd8dabfd48a

**Comment by gares** [comment]
the commit fixes things, but the logic for giving the right message to the user was already duplicated between Coq and CoqIDE... how nice

**Comment by psteckler** [comment]
Bad! Bad!

**Comment by gares** [comment]
Fixing things would mean completely erasing that case analysis on the goals data structure in CoqIDE.
And have Coq feedback such message when one prints the goals in structured format.

**Comment by gares** [comment]
The messages are attached to the text when printed in ASCII format.

**Comment by psteckler** [comment]
In printing/printer.ml, pr_open_subgoals creates info feedbacks in some goal situations. In the situation in this issue, it does not, apparently. Would adding the feedback there, or in pr_subgoals, be the fix here?

**Comment by gares** [comment]
I'm not sure this is the function called by ideslave.ml to answer a goal message.  If so, that is the fix I had in mind.

**Comment by psteckler** [comment]
I just tried adding a Feedback.msg_info there, but it does not seem to appear in the XML.

**Comment by ejgallego** [comment]
As Enrico said this is not function called. But I'm a bit lost here, this seems like an IDE specific message (for instance that would be localized) why can't proof general just print the information it wants? Goal display seems quite IDE-specific to me, doesn't it?

**Comment by psteckler** [comment]
That same message is printed by coqtop in its REPL. In vanilla PG, the coqtop message shows up in the \*response\* buffer. An IDE could print additional information, if it wants, sure, but this one should come from coqtop.

**Comment by psteckler** [comment]
If no one objects, I'm going to close this issue, because the main thing was display of background goals, which is fixed.

I'd say the missing feedback is a Coq bug, and I should file a Coq bug report (not sure how to fix this myself).

**Comment by ejgallego** [comment]
Hi Paul, if you want Coq itself to generate the message you have two options:

- uniformize the two codepaths present in coq/coq@1e9ef2c64dcfa916ba3643b219040cd8dabfd48a
- add the desired feedback here: https://github.com/coq/coq/blob/trunk/ide/ide_slave.ml#L215

**Comment by psteckler** [comment]
Simply calling `pr_open_subgoals' at the beginning of `goals' in ide_slave.ml makes the desired feedback appear. 

If we do that, can we rip out the messages that CoqIDE uses? In fact, with the feedback present, the message appears twice!

**Comment by ejgallego** [comment]
If that works it would be great IMO.

**Comment by psteckler** [comment]
That change generates the feedback, but bad things happen, like spurious error messages.

I'm going to close this issue, and put something in Bugzilla to remind us to look at this.

**Comment by jonleivent** [comment]
With bulletted subgoals, I now get a "Background Goals" division in the goals window, with one of the non-focused goals completely shown (with context) and the others showing just their conclusions.  This is unlike vanilla PG and CoqIDE.  However, that's not a bad thing!  In fact, this may be (if it is tweaked a bit) a big improvement...

Is there a way to control this behavior?  For instance, having the first background goal show its context isn't very useful - and is confusing when there are other focused goals (which are more important) that don't show their contexts.  Also, "Background" is an ambiguous word here, especially in light of async proving - maybe "Unfocused" would be better?

I also noticed another division of "Shelved goals" appearing when I shelve one or more goal - again with the first showing its context.  Same issue there - the context of the first such goal isn't very useful to show.  Can it be switched off?

I'd also try to save on vertical screen space by combining header lines and ditching as many blank lines as I could before making it unreadable.  That vertical screen space will be at a premium with this additional goal info (much worse if you can't shut off showing the contexts of the first "Background" and "Shelved" goals).

This is PG xml version 950163c, Coq 8.6 version 024cf5a.

**Comment by jonleivent** [comment]
Here's a screenshot:
![screenshot-emacs jess home-4](https://cloud.githubusercontent.com/assets/7363878/19015737/065970b0-87d8-11e6-8255-f28cd32b58c6.png)

Shows lots of wasted vertical space (gets worse with less trivial contexts, obviously), and also shows those worthless contexts for the first Background and Shelved goals.  It's easy to get confused about where one is among those goals...

Here's a side-by-side of what I'd rather see:
![screenshot-emacs jess home-5](https://cloud.githubusercontent.com/assets/7363878/19015779/f41627e4-87d8-11e6-9e2d-2c7010979c0d.png)

But it would be nice to be able to selectively show the contexts of those other subgoals on demand...

**Comment by psteckler** [comment]
"Background" is the terminology used in the OCaml code for these goals, the XML protocol doesn't associate any name, so I can print anything for them.

I'll tweak the output, not printing context for anything but the first goal in focus, and removing some whitespace.

**Comment by psteckler** [comment]
I've done some tweaking of the goals formatting, see if it's suitable.

**Comment by ejgallego** [comment]
@psteckler what do mean for "associating a name" ? Does the `goal_id` do not serve that purpose?

**Comment by psteckler** [comment]
@ejgallego I just mean that the XML protocol returns 4 lists of goals, without giving a name to any of the lists. It could say something suggestive like:
`<shelved_goals><list>...</list><shelved_goals>`
but the XML doesn't have anything like that.

**Comment by ejgallego** [comment]
Oh, I see, I guess I got too used to have proper record serialization. Currently, the record representing the output of goals is:
```ocaml
type 'a pre_goals = {
  fg_goals : 'a list;
  (** List of the focussed goals *)
  bg_goals : ('a list * 'a list) list;
  (** Zipper representing the unfocused background goals *)
  shelved_goals : 'a list;
  (** List of the goals on the shelf. *)
  given_up_goals : 'a list;
  (** List of the goals that have been given up *)
}
```
and they are outputted in this order, but note that there's nothing maintaining the order invariant in the serialization. Thus, it seems a bit fragile.

**Comment by jonleivent** [comment]
I like the new format.  It could be vertically compressed even further, but this is certainly good enough.

**Comment by jonleivent** [comment]
Wait - not working yet.  Try single stepping through the find function in wavl-noauto.v.  Goals window display seems to go right until within the second "*" bullet, then the non-focused goals are lost, and it reverts to saying "No more goals" at the end of that bullet:
![screenshot-emacs jess home-6](https://cloud.githubusercontent.com/assets/7363878/19061263/5e230d7e-89bd-11e6-85d2-957333449209.png)

This is PG xml version 331dc4f, Coq 8.6 version 6cc37a6

**Comment by jonleivent** [comment]
I think I see one problem - the Unfocused goals only count those that lost focus at the current bullet entrance, not those unfocused by outer bullets.  Hence, when leaving a bullet that lost outer unfocused goals, those outer unfocused goals don't reappear in the Unfocused list.  In other words, there should be a stack of Unfocused (and probably Shelved) goals operating (although they don't have to be displayed as a stack), but instead there is just one bullet's worth.

**Comment by psteckler** [comment]
PG is simply displaying the goals that Coq hands off to it. I think that adding a stack discipline informed by the bullet structure would be better handled on the Coq side.

The "No more subgoals" display is a bug -- Coq is sending a nonempty list of goals in that case. I'll track it down.

**Comment by psteckler** [comment]
When Coq sends its "background" goals, they come in the form of a list of pairs, where each pair contains two lists. In what I've seen so far, the first element of the pair has always been an empty list, so I'm not sure how to process it. The second element of the pair is a list of goals. PG was only looking at the first pair in the list of pairs, and sometimes, it seems, both elements of the pair are empty lists, leading to the "No more subgoals" message.

I've committed a fix where all background/unfocused pairs are displayed, see if that helps.

**Comment by jonleivent** [comment]
This version (ba90b61) works better.  However, a slight issue in that sometimes, one sees "*** Unfocused goals *** 0 subgoals", as here:

![screenshot-emacs jess home-7](https://cloud.githubusercontent.com/assets/7363878/19120805/3a4cca94-8af2-11e6-9313-89075e3cd687.png)

Probably not worth attempting to fix this, unless it is very obvious what to do.

**Comment by psteckler** [comment]
I've fixed this bug in the code, will commit shortly.

CJ Bell worked out the structure of the "background goals" in the XML; I'm working on presenting that. I'll see if I can remove some whitespace, too.

**Comment by psteckler** [comment]
I've committed code that shows all the "background goals", should also fix 0 subgoals bug, and remove some whitespace.

**Comment by jonleivent** [comment]
What does the "after focus" in "*** Unfocused (after focus) goals ***" mean?

**Comment by psteckler** [comment]
As CJ worked out, the "background goals" given in the XML represent a tree of goals, which is presented as a list of pairs, where each pair consists of two list of goals. His explanation is here:
[https://github.com/siegebell/vscoq/blob/master/CoqProtocol.md#command-goal](url)

**Comment by psteckler** [comment]
The issue originally reported here has been fixed, so closing.
