### ISSUE TITLE
PGxml makes goal line too long sometimes

### ISSUE THREAD

**Issue by jonleivent** [psteckler/ProofGeneral#37]
This is PGxml version 40e991b (Emacs 24.4.1, Coq 8.6 version d907342):

![screenshot-emacs jess home-2](https://cloud.githubusercontent.com/assets/7363878/18925430/f830b6fe-8581-11e6-8c95-079d97b1baaa.png)

Compare to normal PG (version 71be0c6):

![screenshot-emacs jess home-3](https://cloud.githubusercontent.com/assets/7363878/18925459/16a65918-8582-11e6-9c09-4209c7a1761b.png)

**Comment by psteckler** [comment]
Hmmm, I thought I'd fixed this bug. I'm seeing different behavior for this same file:

![goals](https://cloud.githubusercontent.com/assets/2244648/18931980/8206316e-859c-11e6-936f-a6b27aa4dd53.png)

Does "make clean && make" change anything?

**Comment by jonleivent** [comment]
Just did a git pull, git clean -f, make clean, make.  Still the same result.  I noticed your window has an unbroken line while I have dashes.  Perhaps you have some other mode loaded that fixes things?  Or some other setting?

**Comment by psteckler** [comment]
Let's see, what character set does your Emacs use? UTF-8, or something else?

In coq/coq-server.el, there's a definition at https://github.com/psteckler/ProofGeneral/blob/server-protocol/coq/coq-server.el#L101 :

`(defvar impl-bar-char ?―)`

What happens if you change the character there to something else and recompile?

**Comment by jonleivent** [comment]
Yes - if I make impl-bar-char use a standard ASCII underscore, then there is no more problem.  So, I guess Emacs' mystical rules (ask Clement) about combining fonts for special characters is somehow not providing you with a consistent width for the character you're using in all fonts.  The default font I have set is `(:family "Inconsolata" :foundry "unknown" :slant normal :weight normal :height 120 :width normal)`.

**Comment by psteckler** [comment]
I installed the Inconsolata fonts on Linux Mint 18, and in Emacs, set Inconsolata Medium 12 pt as the default font. And behold, I see the too-long separator.

**Comment by jonleivent** [comment]
But, hey, nice font, right?

Anyway, I'm sure Clement would know the necessary incantation that will tell Emacs you want just enough of those separator chars for the width of the buffer.

**Comment by psteckler** [comment]
Try using this definition:
 `(defvar impl-bar-char #x2014)`

That's an em-dash (a dash the width of 'm'). In Inconsolata, that makes a not-quite-solid line of the right length. It seems that the horizontal bar character I was using is longer than usual in Inconsolata. Maybe I can compensate for that somehow.

**Comment by jonleivent** [comment]
Nope - still too wide for me.
I have no problem using normal ASCII "=" or "_" until this is truly figured out.

**Comment by psteckler** [comment]
Clement points out that Inconsolata doesn't have the horizontal bar character (nor the em-dash), which explains the behavior. 

What's the right thing to do here? If you want to stick with Inconsolata, maybe that's to use your own choice of separator character. 

There don't seem to be Elisp functions to get the pixel-width of characters that would allow compensating for differing display widths.

**Comment by jonleivent** [comment]
I just put this in my coq-mode-hook: `(setq impl-bar-char ?_)` (that's normal ASCII underscore)

The fact that this isn't as breathtakingly beautiful as Company-Coq's solid buffer-spanning line is not nearly as important as that it doesn't wrap.  Anyway, I assume that eventually your xml-PG and Company-Coq will have to get on speaking terms, at which point, the problem might go away.

**Comment by psteckler** [comment]
Do you prefer the buffer-spanning line?

I was calculating the width based on the widths of the hyps and goal.

**Comment by jonleivent** [comment]
I don't care that much, as long as it doesn't wrap, and isn't too ugly.  I survived without a buffer-spanning line prior to Company-Coq, I can do it again!

**Comment by psteckler** [comment]
OK, can we close this one for now?

**Comment by jonleivent** [comment]
OK by me.
