### ISSUE TITLE
"Wrong type argument: number-or-marker-p, nil" when restarting after ^C^X, but only rarely

### ISSUE THREAD

**Issue by jonleivent** [psteckler/ProofGeneral#39]
This is very hard to reproduce.  I've only been able to do it twice, both times with -async-proofs lazy on.  Approximately how this was done: lazily process most of the buffer, wait, ^C^X to stop coqtop, then toolbar GoTo a point down far in the buffer.

**Comment by jonleivent** [comment]
Happened again - and when it happens, the only thing that will stop it is exit emacs and restart.

This time it happened after stopping -async-proofs lazy mode, setting to non-lazy, and restarting.

**Comment by psteckler** [comment]
Oh joy, a Heisenbug.

I haven't looked at C-c C-x, but I will do.

**Comment by psteckler** [comment]
You might want to add this somewhere:

  (setq debug-on-error t)

That should give you a stack trace if the error occurs again, so we can track down its location.

**Comment by psteckler** [comment]
Has this bug shown up recently? 

I've made changes that removed that particular type error, which may have fixed this bug.

**Comment by jonleivent** [comment]
I have not been able to reproduce it.

**Comment by psteckler** [comment]
OK, I'm going to close this issue, but please re-open it if the bug re-surfaces.
