### ISSUE TITLE
Funny error behavior

### ISSUE THREAD

**Issue by ejgallego** [psteckler/ProofGeneral#42]
Emacs 25, coq 8.6. I am not sure this is not a bug in Coq itself, load the following script and go to point here marked:
```coq
Lemma srP P (H : semiReflect P) : reflect P (sr_true H).

About id.

Inductive semiReflect (P : Prop) : Set :=
| PTrue  :   P -> semiReflect P
| PFalse : ~ P -> semiReflect P.

Lemma srP P (H : semiReflect P) : reflect P (sr_true H).
(* Go to point there *)
```
PG and Coq seem to lose document consistency.

**Comment by ejgallego** [comment]
It could be the case that the error-resilience code is a bit immature to be enabled by default.

**Comment by ejgallego** [comment]
Here's the log:

```elisp
(StmAdded 2 ... NewTip)
(StmAdded 3 ... NewTip)
(StmAdded 5 ... NewTip)
(StmAdded 6 ... NewTip)
(Control (StmObserve 6))
(Feedback ((id (State 6)) (contents (ProcessingIn master)) (route 0)))
(Feedback ((id (State 5)) (contents (ProcessingIn master)) (route 0)))
(Feedback ((id (State 3)) (contents (ProcessingIn master)) (route 0)))
(Feedback ((id (State 2)) (contents (ProcessingIn master)) (route 0)))
(Feedback ((id (State 1)) (contents Processed) (route 0)))
(Feedback ((id (State 2)) (contents (Message Error
        " The reference semiReflect was not found in the current environment."))))
(Feedback ((id (State 3)) (contents (Message Notice () "..."))))
(Feedback ((id (State 3)) (contents Processed) (route 0)))
(Feedback ((id (State 5)) (contents Processed) (route 0)))
(Feedback ((id (State 4)) (contents (ProcessingIn master)) (route 0)))
(Feedback ((id (State 2)) (contents Processed) (route 0)))
(Feedback ((id (State 4)) (contents (Message Error)  (PCData " semiReflect already exists."))))
(Answer 1 (CoqExn (loc) ((2 4)) (Cerrors.EvaluatedError "Error: semiReflect already exists.")))
```
Uh, Coq reports on a non-existing state... This looks bad.

**Comment by ejgallego** [comment]
Trying to `EditAt` seems broken too:
```
(Control (StmEditAt 2))
(Feedback ((id (State 2)) (contents Processed) (route 0)))
(Answer 2 (CoqExn loc ((1 2)) (Cerrors.EvaluatedError
   "Error: The reference semiReflect was not found in the current environment.")))
```
In the sense we have to cascade errors out:
```
(Control (StmEditAt 1))
(Feedback ((id (State 1)) (contents Processed) (route 0)))
(Answer 3 (StmEdited NewTip))
(Answer 3 (StmCanceled (6 5 3 2)))
(Answer 3 Completed)
```
At least this brings back things into a consistent state again.

**Comment by psteckler** [comment]
In PG, I see a feedback with an invalid state id of 5 (that one never appears in a good-value), but the fail-value has a valid state id of 3, and PG can do an Edit_at back to that state.

That's a bit funny, though, because 3 is the state id after the first line, which contains an error. That may be correct behavior, because when that line was Add'ed, Coq's response was a good-value with state id 3.

**Comment by ejgallego** [comment]
I guess that is the same sequence modulo some initial Add PG does. Anyways, this looks like a bug in Coq, do you agree?

Not sure what could PG do here as not to get confused as it does.

**Comment by psteckler** [comment]
I agree that the invalid state id (5 in the case of PG) is a bug. Why the state id's go 1,3,4,6 isn't clear to me. Somewhere inside Coq, a 5 was generated, but never sent.

The state id of 3 in the fail-value is OK, I think. Do you agree?

**Comment by ejgallego** [comment]
We already noticed that STM is creating some hidden states (we noticed in SerAPI) and indeed this creates many problems to simplify the protocol. I guess that it comes from inserting a dummy definition for `semiReflect`. I agree the error on the hidden state is a bug.

The fail value is OK from a "technical" point of view, but extremely confusing, don't you think? You execute an statement and suddenly you find yourself way back on the document.

**Comment by psteckler** [comment]
Since there are known-good state id's later in the document, Coq could choose one of them. So yes, maybe it's not a good choice.

**Comment by ejgallego** [comment]
Yeah, it is tricky, I still couldn't really make my mind on what is the optimal error handling strategy for the `Add/Cancel` protocol.

So I'll move this bug upstream, and test again (and close properly) to see if PG doesn't get confused.

**Comment by ejgallego** [comment]
Upstream bug: https://coq.inria.fr/bugs/show_bug.cgi?id=5118

**Comment by gares** [comment]
Blind guess: if you remove the outer lemma then things work.  If so, I'll disable command-error-resiliency for non-toplevel commands.

**Comment by ejgallego** [comment]
Hi Enrico, oh good catch, I didn't write a proof (or `Admitted`) frankly as I forgot (due to the first error). Indeed if you do that things seem to work, let me explore a bit more.

**Comment by ejgallego** [comment]
Ok, I confirm that without nested commands, things do work much better. So indeed at least in my IDE efforts I'm going to declare nested stuff "not supported".

**Comment by psteckler** [comment]
OK, should I close this as a PG issue?

**Comment by psteckler** [comment]
Closing ...

**Comment by ejgallego** [comment]
Yeah you can close this unless you want to investigate why PG kind of becomes unsynchronized (likely lack of cascade error handling)
