### ISSUE TITLE
"retracted span" is not very useful; it'd be more useful to display the error message that caused the retraction

### ISSUE THREAD

**Issue by JasonGross** [psteckler/ProofGeneral#44]
![image](https://cloud.githubusercontent.com/assets/396076/19090245/8a434494-8a4b-11e6-85c9-d3fd6d965ac0.png)

**Comment by psteckler** [comment]
I changed the messages to use proof-debug-message, whose display is opt-in.

**Comment by psteckler** [comment]
Closing.
