### ISSUE TITLE
C-g should not result in "Error in process filter: Quit"

### ISSUE THREAD

**Issue by JasonGross** [psteckler/ProofGeneral#46]

**Comment by psteckler** [comment]
The Emacs manual says that quitting in process filters is inhibited by default:
[https://www.gnu.org/software/emacs/manual/html_node/elisp/Filter-Functions.html](url)
so this shouldn't happen.

How can I reproduce the bug?

**Comment by psteckler** [comment]
I've verified that inhibit-quit is t when the process filter is running.

I'm about to commit code that sets inhibit-quit to t in some other strategic places where inconsistency might result.

**Comment by psteckler** [comment]
I can't make this happen with the current code (I think I did once before).

Closing, but please re-open if it occurs again (and detail the steps to make it happen).
