### ISSUE TITLE
"error in process filter: Variable binding depth exceeds max-specpdl-size"

### ISSUE THREAD

**Issue by JasonGross** [psteckler/ProofGeneral#51]
![image](https://cloud.githubusercontent.com/assets/396076/19092802/77b87758-8a56-11e6-8ec0-09a2b53fb9aa.png)

I can't tell you how to reproduce it, except that it involves spamming `C-g` a lot.

**Comment by psteckler** [comment]
I managed to get this behavior, inadvertently.

I believe the behavior is caused by `tq-process-buffer', which uses a loop expressed via recursion. Probably Elisp doesn't do proper tail recursion. 

We can fix that by using a while loop. Programming 101.

**Comment by psteckler** [comment]
I made the loop.
