### ISSUE TITLE
Queue feedbacks for unseen state id's

### ISSUE THREAD

**Issue by psteckler** [psteckler/ProofGeneral#53]
For ParalITP.v, after fixing the proof, the processingin and processed feedbacks for the Qed come before the value that closes the focus. If those are ignored, the Qed never gets colored properly.

**Comment by ejgallego** [comment]
As we have discussed this is IMO a serious protocol design issue and should be addressed upstream.

I think that the best solution would be to allow the user to pick the state name at `Add` time, as suggested by Clément. That modification would solve this and other issues.

**Comment by psteckler** [comment]
Sure, but I can do a workaround in the meantime.

**Comment by ejgallego** [comment]
I got a patch almost ready that changes the semantics of `Add` to require the client to name the next `Stateid.t` It thus removes the `Stateid.t` from the answer. Let's see what other devs think.

Unfortunately this change breaks the protocol, but it eases many things: in particular, you don't have to wait for the answer.

**Comment by psteckler** [comment]
Will the patch be applicable to 8.5? PG needs to run with 8.5.

**Comment by ejgallego** [comment]
I'm afraid the change will be too much for 8.5, likely even for 8.6, even if it fixes a good array of bugs.

AFAIU the XML protocol is of "experimental" nature, and for sure 8.7 should bring many changes to fix bugs and problems. Due that the protocol itself seems to need some fixes it is going to be hard to maintain compatibility.

**Comment by ejgallego** [comment]
Support should be possible by having different code paths in PG, it is annoying but should matter so much, as in a sense the changes to the protocol are supposed to simplify PG code.

In particular, for this problem, the protocol allows the feedback queue to grow unbounded, so I think it would be welcome not having to maintain a queue and replay events (with implies quite a few race conditions)

**Comment by psteckler** [comment]
Done.
