### ISSUE TITLE
server-protocol branch should be GitHub default

### ISSUE THREAD

**Issue by tchajed** [psteckler/ProofGeneral#55]
You can make GitHub display the server-protocol branch by default, as well as cause git clone to default to the server-protocol branch, by [setting the default branch](https://help.github.com/articles/setting-the-default-branch/) on GitHub. This would make the installation instructions the same as for PG, other than using this repo rather than https://github.com/ProofGeneral/PG.

**Comment by psteckler** [comment]
Done!
