### ISSUE TITLE
PGxml sometimes omits spaces in goals window conclusions.

### ISSUE THREAD

**Issue by jonleivent** [psteckler/ProofGeneral#56]
![screenshot-emacs jess home-8](https://cloud.githubusercontent.com/assets/7363878/20193798/a0e11ba2-a75d-11e6-9b2a-5b0479487868.png)

Note that this cannot be a font issue, as `findResult x c` appears OK in the `find` hyp, just not in the conclusion.  I have only seen the problem in the conclusions.

This is PGxml version b5794da, Coq 8.6 version 6402782, GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.5)

**Comment by psteckler** [comment]
Can you enable traffic logging (set proof-server-log-traffic to t, or set it in generic/proof-config.el), and see what the XML in the **coq-log** buffer is when this happens?

**Comment by psteckler** [comment]
With 8.5pl2, I see this XML:

`<value val="good"><option val="some"><goals><list><goal><string>58</string><list><string>find&nbsp;:&nbsp;forall&nbsp;(x&nbsp;:&nbsp;A)&nbsp;(k&nbsp;:&nbsp;EZ)&nbsp;(g&nbsp;lg&nbsp;rg&nbsp;:&nbsp;EB)&nbsp;(c&nbsp;:&nbsp;EL),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;wavltree&nbsp;k&nbsp;g&nbsp;lg&nbsp;rg&nbsp;c&nbsp;-&gt;&nbsp;findResult&nbsp;x&nbsp;c</string><string>x&nbsp;:&nbsp;A</string><string>k&nbsp;:&nbsp;EZ</string><string>g,&nbsp;lg,&nbsp;rg&nbsp;:&nbsp;EB</string><string>c&nbsp;:&nbsp;EL</string><string>w&nbsp;:&nbsp;wavltree&nbsp;k&nbsp;g&nbsp;lg&nbsp;rg&nbsp;c</string></list><string>findResult&nbsp;x&nbsp;c</string></goal></list><list/><list/><list/></goals></option></value>`

There are non-breaking spaces that should separate `findResult` from `x` and `c`.

**Comment by jonleivent** [comment]
I get this:
`<value val="good"><option val="some"><goals><list><goal><string>58</string><list><richpp><_>find&nbsp;:&nbsp;<constr.keyword>forall</constr.keyword>&nbsp;(x&nbsp;:&nbsp;<constr.reference>A</constr.reference>)&nbsp;(k&nbsp;:&nbsp;<constr.reference>EZ</constr.reference>)&nbsp;(g&nbsp;lg&nbsp;rg&nbsp;:&nbsp;<constr.reference>EB</constr.reference>)&nbsp;(c&nbsp;:&nbsp;<constr.reference>EL</constr.reference>),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<constr.reference>wavltree</constr.reference>&nbsp;<constr.variable>k</constr.variable>&nbsp;<constr.variable>g</constr.variable>&nbsp;<constr.variable>lg</constr.variable>&nbsp;<constr.variable>rg</constr.variable>&nbsp;<constr.variable>c</constr.variable>&nbsp;<constr.notation>-&gt;</constr.notation>&nbsp;<constr.reference>findResult</constr.reference>&nbsp;<constr.variable>x</constr.variable>&nbsp;<constr.variable>c</constr.variable></_></richpp><richpp><_>x&nbsp;:&nbsp;<constr.reference>A</constr.reference></_></richpp><richpp><_>k&nbsp;:&nbsp;<constr.reference>EZ</constr.reference></_></richpp><richpp><_>g,&nbsp;lg,&nbsp;rg&nbsp;:&nbsp;<constr.reference>EB</constr.reference></_></richpp><richpp><_>c&nbsp;:&nbsp;<constr.reference>EL</constr.reference></_></richpp><richpp><_>w&nbsp;:&nbsp;<constr.reference>wavltree</constr.reference>&nbsp;<constr.variable>k</constr.variable>&nbsp;<constr.variable>g</constr.variable>&nbsp;<constr.variable>lg</constr.variable>&nbsp;<constr.variable>rg</constr.variable>&nbsp;<constr.variable>c</constr.variable></_></richpp></list><richpp><_><constr.reference>findResult</constr.reference>&nbsp;<constr.variable>x</constr.variable>&nbsp;<constr.variable>c</constr.variable></_></richpp></goal></list><list/><list/><list/></goals></option></value>`

**Comment by psteckler** [comment]
OK, the code I have of yours does not run with 8.6 -- but I'm able to reproduce the error by pasting in this response into the PG code. Looking into it, thanks!

**Comment by psteckler** [comment]
In 8.6, a `&nbsp;` inside of `<richpp>` tags indicates whitespace that's meant for formatting. Elsewhere, `&nbsp` is used to indicate structure. Currently, PG unescapes all the `&nbsp;` to spaces. When the resulting string is parsed into an Elisp s-expression, the formatting intent is lost.

PG can replace the `&nbsp;` inside of `<richpp>` tags with some special token that survives the change to spaces and XML parsing, then is replaced with spaces again for the final formatting.

The other solution would be to insert such a token on the Coq side in place of `&nbsp;`, but maybe that's too much trouble.

**Comment by psteckler** [comment]
That approach works, but it takes considerable time.

In fact, I could not work out why the spacing looks OK in the hypotheses.

**Comment by psteckler** [comment]
I'm doing the string replacement in a naive way. I can think of faster ways to do this.

**Comment by psteckler** [comment]
I think my earlier claim that &nbsp; can be used structurally in 8.6 is not right, it's always used for formatting. So I can replace it universally with a special token to preserve formatting before parsing XML to an S-expression (always within richpp tags), later replace the token with a space.

I've committed code to do that, see if it works.

**Comment by jonleivent** [comment]
That works!

**Comment by psteckler** [comment]
Great, let me know if I've broken anything with the fix. :-)
