### ISSUE TITLE
Text editing commands in processed regions should both retract the buffer and edit

### ISSUE THREAD

**Issue by JasonGross** [psteckler/ProofGeneral#58]
I should not have to paste something 2-3 times in a processed region to get it to paste.  `C-BACKSPACE` should not move the cursor without deleting text.

**Comment by psteckler** [comment]
I've committed code that I believe fixes the issue, please try it!

**Comment by psteckler** [comment]
I'm closing this one, since I think it's fixed. Please re-open if not.
