### ISSUE TITLE
Clicking "check" gives no feedback

### ISSUE THREAD

**Issue by JasonGross** [psteckler/ProofGeneral#61]
![vokoscreen-2016-11-28_16-59-56](https://cloud.githubusercontent.com/assets/396076/20687861/31396f2e-b58c-11e6-8316-7585a835549a.gif)

**Comment by psteckler** [comment]
Hmmm, what sort of feedback do you think there should be?

The Check button only is useful if the next-to-last number on the mode line is greater than 0. We could disable the button for the zero case (but some people may choose to run PG without the mode line indicators).

**Comment by JasonGross** [comment]
Either "all proofs successfully checked" or "there were *n* errors" + moving the cursor to the first error.

**Comment by psteckler** [comment]
When the Check button is clicked, PG gets feedbacks indicating which Qeds are considered "complete" by the kernel. When the incomplete count becomes 0, we could print a message that all proofs are complete, though this is no more informative than the count on the mode line.

There isn't a message from Coq, as far as I see, that indicates that some proofs have failed in response to the Check request. A Check request can cause a backtrack to an error, I've noticed, although may not be the first error in the script. We could warp the cursor to that location, though that should be optional.

**Comment by psteckler** [comment]
I've added a message when all proof terms succeed. It shows up in the minibuffer / \*Messages\* buffer.

Limitation: it only shows up when the header line is enabled, because that's where the incomplete count is maintained.

**Comment by psteckler** [comment]
I ran an experiment with a script containing several proofs whose proof terms don't kernel-check (in this case, the proof uses unguarded cofixes). Running "Check" causes Coq to return a single fail-value corresponding to a particular proof term. Running it again reveals the next error, and so on.

**Comment by psteckler** [comment]
I've committed code that moves the point to the location of the error on a "Check".

Closing issue.
