### ISSUE TITLE
There's no buffer with the interaction with Coq

### ISSUE THREAD

**Issue by JasonGross** [psteckler/ProofGeneral#63]
At the very least, error messages like "Coq exited abnormally" and "Bad XML received" should tell me how to view the raw interaction buffer.

**Comment by psteckler** [comment]
The \*coq-log\* buffer only exists if you enable it, by setting proof-server-log-traffic to non-nil.

If you haven't enabled it, there's no such buffer. I can change the default, but I had disabled it to squeeze some more speed. It actually doesn't take a lot of time, I believe, unless you view it, which appears to trigger SGML-formatting of the contents.

**Comment by JasonGross** [comment]
I think I'm fine with it being disabled by default, as long as the critical error messages (things indicating bad interaction with Coq) contain instructions to enable it.

**Comment by psteckler** [comment]
I added an interactive command, M-x proof-server-enable-logging, which can turn on logging in the middle of a Coq session. The message boxes when there's bad XML or a Coq crash mention the command now.
