### ISSUE TITLE
"Number of proofs not yet kernel-checked" does not reach 0

### ISSUE THREAD

**Issue by RalfJung** [psteckler/ProofGeneral#65]
## Steps to reproduce:

* Clone <https://gitlab.mpi-sws.org/FP/iris-coq/>
* Open `theories/prelude/base.v`
* Do C-c C-b to process the entire buffer
* Wait a little

## Expected behavior

The number in the emacs status row described as "Number of proofs not yet kernel-checked" should eventually reach 0 as everything gets checked.

## Actual behavior

The number never seems to decrease. For the particular file above, it stays at 72.

**Comment by psteckler** [comment]
Did you press the Check button, as you would in CoqIDE?

**Comment by RalfJung** [comment]
I didn't press any button, nor did I ever use CoqIDE... I don't even see any button. The toolbar is disabled to save space. But I found "Proof General - Check", and then the number goes down to 0.

So I guess the display was right after all, I just did not know that Qeds are *not* checked by the kernel per default in async mode.

**Comment by RalfJung** [comment]
Is there a way to also add Qed kernel checking to the things that are asynchronously done in background so I don't have ti do "Check" manually?

**Comment by psteckler** [comment]
We can think about doing that when all statements have been processed.
