### ISSUE TITLE
Confusing percentages in status bar

### ISSUE THREAD

**Issue by RalfJung** [psteckler/ProofGeneral#66]
I am not sure I understand the two percentages at the bottom. The main thing I would be interested in is: how long until I can work interactively? If I understand correctly what is displayed, that's the *sum* of the two numbers, so it's actually not so easy to see how far that one is.

Maybe it would be useful to show "% of statement sent to Coq" (i.e., the thing that has to be at 100% to work interactively), and then either of the current ones to see whether there's still background work to be done?

**Comment by psteckler** [comment]
The first percentage refers to statements still being processed by Coq,
relative to the number of statements examined in the buffer. It should go
to 0. The second is the percentage of statements that Coq has finished
processing. It should go to 100%.

**Comment by RalfJung** [comment]
> The second is the percentage of statements that Coq has finished processing. It should go to 100%.

Right, but it'll only become 100 when processing is finished, i.e. in the same moment that the other number reaches 0... or not?

**Comment by psteckler** [comment]
Yes, though the two may not always sum to 100, because Coq may not have
seen or acknowledged all statements.

**Comment by psteckler** [comment]
You can rely on the 2nd percentage, the one that goes to 100%, to know when you can work interactively.

The 1st percentage may be 0, if there are statements sent to Coq that have not been acknowledged.

I could add a 3rd percentage to account for those. Then the sum of the 3 percentages would always be 100. But I think that might make the interface too busy.

**Comment by RalfJung** [comment]
> You can rely on the 2nd percentage, the one that goes to 100%, to know when you can work interactively.

I cannot confirm this.  That percentage keeps going even after the "interactive focus" is at the requested position. It only reaches 100% when all the "delayed" proofs are completed.

(Actually, it sometimes never reaches 100% here. Unfortunately, I could not reproduce this.)

**Comment by RalfJung** [comment]
Actually, the "does not reach 100%" is kind of reproducible here:
* Check out https://gitlab.mpi-sws.org/FP/iris-coq/ at 16b514a87088235a815fd374198420fc74186896
* Do "make quick" to have all the vio files
* Open theories/algebra/agree.v and jump to line 8 (the first blank line)

Percentage only goes up to 50% here. If I C-c C-x Coq and do the same again, it reaches 50%, stays there for ~0.5 seconds, then goes to 100%; the bug only happens the first time after startup.

I didn't see anything useful in `*Messages*` or so; let me know if there is a way that I can capture a log that is useful for you.

**Comment by RalfJung** [comment]
I learned about proof-server-enable-logging, here's the log of reproducing the above issue:
[log.txt](https://github.com/psteckler/ProofGeneral/files/737518/log.txt)

**Comment by RalfJung** [comment]
Sorry, seems that log was from another file (probably `heap_lang/lib/barrier/proof.v`). Here's a log from agree.v:

[log.txt](https://github.com/psteckler/ProofGeneral/files/739938/log.txt)

I only get the 50% problem if this is the very first thing I do after starting emacs. if I do focus Coq somewhere else, and then switch to agree.v and do the same thing, it goes to 100%.

**Comment by psteckler** [comment]
The log looks OK.

My guess is that the header line is not getting updated (which also affects the status line percentages). 

I've created a branch, `header-line-debug`, that prints some messages. Here's what you can try:

  - checkout this branch
  - make clean && make
  - run Emacs, use `make-frame` to create a new window (to easily see new messages)
  - switch that new window to the \*Messages\* buffer
  - run `agree.v` to line 8, as before

Do any new messages appear in \*Messages\* after running the file?

**Comment by RalfJung** [comment]
Hm, I cannot reproduce the issue any more, neither with the head-line-debug branch nor with the "main" branch. :/

So, to pup back up the stack:

> You can rely on the 2nd percentage, the one that goes to 100%, to know when you can work interactively.

I cannot confirm this. Consider the following test file:
```
Lemma foobar: True.
Proof.
do 100000 (do 1000 idtac). exact I.
Qed.

Lemma xtra : True.
Proof.
(* Jump here *)
intros.
```
If I go to the marked position and press C-c C-RET, the 2nd percentage only reaches 100% when the `foobar` proof has been completed. However, I can also work interactively (as in execute the "intros." at the end) way earlier, when the processed region reaches `xtra`.

**Comment by psteckler** [comment]
Maybe I accidentally fixed something. :-)

Yes, using the 100% as the criterion is conservative. Certainly if it reaches 100%, you can proceed, but as this example indicates, often you can do so before that.

In fact, I think as long as you don't try to work in the pink area at the bottom (the part that's been queued but not yet sent to Coq), which is read-only, you should be able to proceed.

**Comment by RalfJung** [comment]
Right, so the point is -- say I open a new file, go to the spot I want to work in, and do C-c C-RET. When can I work interactively? The answer seems to essentially be "when the dark blue region reaches you". That's fine, but it also means that I have yet to find a good reason for why these two percentages should ever be interesting. ;)   The only state there that's at all meaningful (IMHO) is "0%  100%", because it means that one can look for red spots to find bugs.

**Comment by psteckler** [comment]
Basically, I put those in ... because I could. :-)

Those numbers do tell you something about the state of the computation. If people think they're not useful, I can remove them.

**Comment by psteckler** [comment]
I'm going to close this, since there doesn't appear to be a bug to be fixed at this point. Please re-open if needed.
