### ISSUE TITLE
"dark-blue" marking (things left to process) lost on error

### ISSUE THREAD

**Issue by RalfJung** [psteckler/ProofGeneral#67]
## Steps to reproduce:

* Have a file with a long slow proof followed by other proofs
* Jump into some other proof
* While the long slow proof is still ongoing, write & execute a failing tactic

## Expected behavior

* The background process is unaffected, both visually and operationally

## Actual behavior

* The long slow proof changes color from "dark blue" (left to process) to the "very light blue" background color. However, proof processing continues; after some time, more and more of the long slow proof becomes "less light blue" (processed successfully).

Here's a concrete file where this came up; it depends on coq-iris though so it may be too much effort to actually load that file: <https://gitlab.mpi-sws.org/FP/LambdaRust-coq/blob/master/theories/typing/function.v> (You have to replace all "Global Instance" by "Instance" to make things actually async; that's a Coq bug.)

**Comment by psteckler** [comment]
Sorry, I'm not following. I think I need a small, concrete example to understand this issue. You could create a slow proof with timing delays.

I tried to use LambdaRust, but ran into build troubles (though I have Iris installed).

If the failing tactic is in the other proof, and proofs are being processed in async mode, shouldn't the long slow proof continue to be processed? In async mode, a failing tactic doesn't even prevent the proof containing that failure from proceeding.

**Comment by RalfJung** [comment]
Here is a minimal example:
```
Definition t := True.
Hint Opaque t.
Lemma T_T : t -> t. Proof. intros. assumption. Qed.
Hint Resolve T_T.

(* Slow proof. *)
Lemma lem1 : t.
Proof.
auto 500000; exact I.
Qed.

Lemma lem2 : True.
Proof.
(* First, step here. Wait until the interactive focus is here;
   the slow proof above will still be processed. It has a dark blue background
   to indicate that the proof is still being checked. *)
(* Next, execute the following tactic.  The dark blue background of the
   slow proof disappears. *)
fail.
```

**Comment by psteckler** [comment]
Yes, I see the behavior. Investigating.

**Comment by psteckler** [comment]
The `fail` triggers a backtrack. For some reason, there was code to delete all colored spans on a backtrack. I recall there was a file where that was useful, but clearly that's not right in general, so I've committed a fix where that code is removed.

**Comment by RalfJung** [comment]
Confirmed, thanks!
