### ISSUE TITLE
The bar that separates assumptions from goal can get too long (multiple lines)

### ISSUE THREAD

**Issue by RalfJung** [psteckler/ProofGeneral#68]
## Steps to reproduce

* Have an assertion with a name that spans multiple lines
(I know this is not sensible, it's just an easy way to get a line in the premises/conclusion of the goal that's very long, and thus demonstrating this issue).

## Actual behavior

The bar separating assumptions from goal also ends up being multiple lines long, which looks rather wrong:
![spectacle lh1883](https://cloud.githubusercontent.com/assets/330628/21999441/6a08aab6-dc3a-11e6-97ef-fe2a04702913.png)

There should be an upper limit on how long that bar becomes, to avoid it to linebreak. (In PG master, I think the line has fixed length, so it never linebreaks.)

**Comment by psteckler** [comment]
Instead of using a fixed length, I changed the \*goals\* buffer to truncate long lines, as was already done for the \*response\* buffer.

See if this approach works adequately.

**Comment by ejgallego** [comment]
By the way I see your display is botched given richpp doesn't properly set the printing width, see https://github.com/coq/coq/pull/383 . Maybe we could bug the devs to get it merged in 8.6.

p.s: It would be great to hear from emacs folks what your ideal "output rich format" would be. Are you happy with `richpp` ?

**Comment by psteckler** [comment]
Right now, I'm just stripping out the tags inside `richpp` tags. I could give them some display semantics.

The fact that newlines are semantically significant in `richpp` because of the translation to S-expressions, which gave rise to the issue here.

Also, I have to replace the occurrences of `&nbsp;`, because the XML parser doesn't understand them.

What other kind of formatting information could be useful?

**Comment by ejgallego** [comment]
I think more or less what is discussed on CEP009, I was wondering more about what kind of "document format" is easy to render in emacs. Ideally, it would be independent of the display width, etc...

**Comment by psteckler** [comment]
Of course, Emacs is oriented to display text. If Coq offers its own document format, we'd have to write our own interpreter for it. There are packages to display HTML and TeX, not sure how well they work.

**Comment by ejgallego** [comment]
It looks to me like Coq won't change the default output format for a while, you will have text and annotated text (in this slightly weird incarnation).

However, for jsCoq I will use some "HTMLy", box-based format that has a straightforward interpretation by web-browser engines and can do a few tricks. Math will be displayed using TeX.

I was wondering if this could be modified to help emacs in any way, maybe using `shr.el`, but I dunno.

**Comment by psteckler** [comment]
I just tried `shr-render-region` on the HTML from the first page of the Coq manual. The result isn't very nice, actually.

**Comment by psteckler** [comment]
Closing, because the separator line wrap Ralf pointed out should be gone now.

**Comment by RalfJung** [comment]
Indeed it is. I will report back if the lack of line breaks for the other lines in the context is an issue.
