### ISSUE TITLE
"Coq is still working, can't undo yet"

### ISSUE THREAD

**Issue by ejgallego** [psteckler/ProofGeneral#71]
In my normal PG workflow, I often get "Coq is still working, can't undo yet" when going back in a buffer. This is quite annoying for:
a) It displays a modal dialog, requiring me to reach the mouse or perform a windowing operation.
b) Interrupts my usual fast-undo workflow.

Would it be possible to remove or improve this message, thanks?

**Comment by psteckler** [comment]
Would moving the message to the minibuffer help?

With the XML protocol, sometimes it can take awhile for an undo to finish, before you can perform another one.

**Comment by ejgallego** [comment]
The ideal thing would be to queue the command; why can't another `editAt` be issued? But yes, refusing to do the undo and having a minibuffer message would be helpful.

I am also seeing some strange artifacts like having to do undo twice for an undo to happen.

**Comment by psteckler** [comment]
On Wed, Jan 25, 2017 at 11:26 AM, Emilio Jesús Gallego Arias
<notifications@github.com> wrote:
> The ideal thing would be to queue the command; why can't another editAt be issued? But yes, refusing to do the undo and having a minibuffer message would be helpful.

I'm reusing the crusty old generic PG machinery for undo, which relies
on the bounds of the processed region. That region doesn't change
until the previous undo has finished. The EditAt doesn't get queued
until that machinery has run.

Of course, it's possible to change this strategy, particularly if Coq
ends up being the sole PG client (EasyCrypt still seems like a
candidate). For now, I don't want to change this.

I'll move the message to the minibuffer, and remove the modal dialgo.

> I am also seeing some strange artifacts like having to do undo twice for an undo to happen.

You might want to run M-x proof-server-enable-logging, and send the
contents of the \*coq-log\* buffer when that happens, to see what's
happening.

-- Paul

**Comment by ejgallego** [comment]
Cool, thanks. Will test and report back. Other issues moved to #73

**Comment by ejgallego** [comment]
Ok the behavior now is IMO reasonable, thanks!

**Comment by psteckler** [comment]
On Wed, Jan 25, 2017 at 12:32 PM, Emilio Jesús Gallego Arias
<notifications@github.com> wrote:
> Ok the behavior now is IMO reasonable, thanks!

We aim for reasonability when possible! :-)
