### ISSUE TITLE
Feature request: show unfocused goals

### ISSUE THREAD

**Issue by Zimmi48** [psteckler/ProofGeneral#84]
As mentioned in coq/coq#454, it would be great if PG/xml could have a display option to show unfocused goals, similar to what this PR adds both to CoqIDE and coqtop.

This should have however a quite low priority.

**Comment by psteckler** [comment]
Actually, PG/xml already shows unfocused goals (it's "background" goals in the source code), just the goals without hypotheses, by default.

There's already an option to turn this off in the menus, "Hide Additional Subgoals".

**Comment by Zimmi48** [comment]
Well that's great to hear. Sorry for the noise. I was under the impression that no such feature existed and you were asking me to open a feature request.

**Comment by psteckler** [comment]
I had to look at the PR to see what CoqIDE was doing. I thought maybe it was doing more, like printing the hypotheses. 

Sorry to mislead you!

**Comment by Zimmi48** [comment]
No worries. Cheers!
