### ISSUE TITLE
When proof-prog-name-ask is t, the program prompt should default to the current coq executable, not the empty one

### ISSUE THREAD

**Issue by JasonGross** [psteckler/ProofGeneral#85]
In PG-xml:
![image](https://cloud.githubusercontent.com/assets/396076/25556072/227fe95e-2cc4-11e7-943c-26388512b370.png)
In PG:
![image](https://cloud.githubusercontent.com/assets/396076/25556075/32c2cb9c-2cc4-11e7-8779-df50b2cb677f.png)
Note the difference between the default `Run process` field at the bottom; I think it should be auto-filled to a default.

**Comment by psteckler** [comment]
I added the `locate` code used in vanilla PG, so it should work the same now.

I also set `proof-prog-name` in the coq-mode hook, a la vanilla PG. I can't recall why I was using a special hook to set it for the case when `proof-prog-name-ask` was `nil`.

Please try this!

**Comment by psteckler** [comment]
@JasonGross: can I close this?

**Comment by psteckler** [comment]
Closing, fixed AFAIK
