### ISSUE TITLE
Goal buffer should default to scrolling to the goal line, not to the top

### ISSUE THREAD

**Issue by JasonGross** [psteckler/ProofGeneral#88]
In PG-xml:
![image](https://cloud.githubusercontent.com/assets/396076/25556783/4e81d56e-2cd1-11e7-958b-a092abbaee49.png)
In PG:
![image](https://cloud.githubusercontent.com/assets/396076/25556785/53d3e598-2cd1-11e7-85e7-35ce523d80da.png)

**Comment by psteckler** [comment]
Vanilla PG runs something called `coq-show-first-goal`.

I can create something similar. It will be a bit different, because the syntax of what's in the goal buffer has changed.

**Comment by psteckler** [comment]
I was able to use the vanilla PG `coq-show-first-goal` with a bit of modification. Working on that prompted me to move a chunk of other goals-related code to its own file, which makes things a bit cleaner.

Please try out this change.

**Comment by psteckler** [comment]
Closing, fixed AFAIK
