### ISSUE TITLE
Error during header update: (range-error floor -0.0e+NaN)

### ISSUE THREAD

**Issue by JasonGross** [psteckler/ProofGeneral#90]
Sufficiently short files (e.g., `emacs foo.v` and type `Goal True.` and type `C-c C-RET`) give `Error during header update: (range-error floor -0.0e+NaN)`

**Comment by psteckler** [comment]
I've committed a fix, please try it.

**Comment by psteckler** [comment]
@JasonGross : is this fixed?

**Comment by psteckler** [comment]
Closing, fixed AFAIK
