### ISSUE TITLE
Proof process highlighting off by 1 line

### ISSUE THREAD

**Issue by HeikoBecker** [psteckler/ProofGeneral#93]
With the current version of the asynchronous ProofGeneral in `emacs 24.4.1`, the highlighting of the processed region is off by some characters.

Steps to reproduce:

Open a file using the new ProofGeneral mode that contains indentation, then step until next line is indented.

Screenshot using the new ProofGeneral:

![screenshot from 2017-07-27 21-51-02](https://user-images.githubusercontent.com/3237993/28689434-eb009558-7315-11e7-85a7-7038534ae73b.png)

Screenshot using the old ProofGeneral:

![screenshot from 2017-07-27 21-52-08](https://user-images.githubusercontent.com/3237993/28689461-f99908ca-7315-11e7-8d54-81c21ee1c54c.png)

**Comment by psteckler** [comment]
I'm guessing this is an interaction with Company-Coq, which isn't yet supported with this version of PG.

I don't see the behavior with PG without Company-Coq.

**Comment by HeikoBecker** [comment]
I disabled global-company-mode and coq-company-mode, but the issue still persists.
Would a list of running minor and major modes help?

**Comment by psteckler** [comment]
Sure.

**Comment by HeikoBecker** [comment]
```
Enabled minor modes: Auto-Composition Auto-Compression Auto-Encryption
Blink-Cursor Centered-Cursor Electric-Indent Evil Evil-Local
File-Name-Shadow Font-Lock Global-Centered-Cursor Global-Font-Lock
Global-Relative-Line-Numbers Global-Undo-Tree Global-Whitespace Holes
Ivy Line-Number Mouse-Wheel Recentf Relative-Line-Numbers
Shell-Dirtrack Show-Paren Tex-Pdf Tooltip Transient-Mark Undo-Tree Yas
Yas-Global
```

I also noticed that the highlighting becomes strange, when inside a proof:


![screenshot from 2017-07-28 17-54-14](https://user-images.githubusercontent.com/3237993/28725484-db904fb6-73bd-11e7-94b2-513aad302674.png)

**Comment by psteckler** [comment]
That's a lot of stuff. Can you try disabling them, one at a time, to see what's affecting things?

You can use your intuition about which minor modes are likely to be affecting the display.

**Comment by HeikoBecker** [comment]
I am now left with
```
Enabled minor modes: Auto-Composition Global-Undo-Tree Holes
Mouse-Wheel Recentf Shell-Dirtrack Tex-Pdf Transient-Mark
```
but the issue persists.

**Comment by psteckler** [comment]
Can one of those remaining minor modes be responsible for the behavior, then?

**Comment by HeikoBecker** [comment]
I am not particularly sure about this.
I tried running with a minimal config by moving away my configuration files and then adding only
`(load-file "/home/hbecker/Git_Repos/PG_async/generic/proof-site.el")` by executing it in the scratch buffer.
Modes enabled are then 
```
Enabled minor modes: Auto-Composition Auto-Compression Auto-Encryption
Blink-Cursor Electric-Indent File-Name-Shadow Font-Lock
Global-Font-Lock Holes Line-Number Menu-Bar Mouse-Wheel Shell-Dirtrack
Tool-Bar Tooltip Transient-Mark
```
Can you point me to the file that computes how far to push the font-lock (I guess this is what the highlighted lines are called) in proof general?

**Comment by psteckler** [comment]
https://github.com/psteckler/ProofGeneral/blob/server-protocol/generic/proof-script.el#L260

I made a recent change there, which may have affected things.

**Comment by psteckler** [comment]
I've made a change to the algorithm there, can you see if it makes a difference?

**Comment by HeikoBecker** [comment]
I checked out your changes, but the problem persists. 
I tried changing some things and  it seems that it works now. I will open a pull request as soon as I have been able to confirm that it works.

**Comment by HeikoBecker** [comment]
Please forget what I said, my changes broke it, I just did not notice because the proof examples were not big enough.

**Comment by HeikoBecker** [comment]
It looks like my theme was the culprit. I tried out a different one today and it turns out the bug is not present anymore.

**Comment by psteckler** [comment]
Interesting. That's your window manager theme, or something in Emacs?

**Comment by HeikoBecker** [comment]
It was the emacs theme.
