### ISSUE TITLE
C-c C-a (i.e., the shortcut for searchabout) does not work with several words

### ISSUE THREAD

**Issue by jhjourdan** [psteckler/ProofGeneral#94]
If I type C-c C-a and then two words, then proof general tries to send the next command of the buffer instead of sending the SearchAbout command I asked for.

**Comment by psteckler** [comment]
Bug confirmed, looking into it.

**Comment by psteckler** [comment]
Actually, PG/xml uses `Search`, rather than the deprecated `SearchAbout`.

**Comment by psteckler** [comment]
There are two bugs here. 

One is that the arguments to `Search` are enclosed in double-quotes, which generates a failure. The other is that the failure causes an `Add` of the following statement.

**Comment by psteckler** [comment]
@jhjourdan I've committed a fix, not double-quoting `Search` arguments, and not trying to backtrack to a dummy state id. Please see if this works for you.

**Comment by jhjourdan** [comment]
Seems to work, thanks!
