### ISSUE TITLE
Some regions stay blue even after killing the Coq process.

### ISSUE THREAD

**Issue by jhjourdan** [psteckler/ProofGeneral#96]
Consider the following Coq code fragment:

```
Lemma L : False. Proof. exact   I.  Qed.
Lemma L2 : True. Proof. exact I.  Qed.
```

Then C-c C-b.

Then edit the proof of L.

Then C-c C-x.

Lemma L2 stays in blue even though the Coq process hqs been stopped. From there, the state of proof general seems completely inconsistent and the only way to recover a consistent state is to restart emacs.

**Comment by psteckler** [comment]
The "secondary locked region" that's created when editing was not being removed in the procedure that's called when there's a buffer retract. I've pushed that change. I also verified that the state variables and tables are being reset.

Please verify that this is fixed.

**Comment by jhjourdan** [comment]
Thanks, this is fixed.
