### ISSUE TITLE
Editing a red region moves the cursor in an unpredictible way.

### ISSUE THREAD

**Issue by jhjourdan** [psteckler/ProofGeneral#99]
```
1 = 2.
```

C-c C-b provokes a syntax error and marks the command in red.

When editing the red region, the command becomes white again, but the cursor moves at the end of the command, which is very inconvenient because some text is inserted in an hardly predictable region.

The same happens when trying to edit a blue region located before the syntax error.

**Comment by psteckler** [comment]
I think I need more information.

I can hit `C-c C-b` and see the single character `1` marked in red. 

Where do you place the cursor, and what keys do you hit next to make the cursor mis-behave?

**Comment by jhjourdan** [comment]
Well, because you solved #98, this Coq script no longer shows `1=2.` in red, so this script no longer triggers the issue.

Is there any way to show a region of Coq code in red?

**Comment by psteckler** [comment]
Try stepping through:

```
Goal True.
  blahblah.
```

The text `blahblah.` should become red (after first turning yellow).

**Comment by jhjourdan** [comment]
Apparently, the kind of "red area" was not the same as this one.

I'm no longer able to reproduce the bug. I'm closing it, I'll re-open it if I run into the issue again.
